### ISSUE TITLE
The location of the sumo credentials file breaks the rails convention

### ISSUE THREAD

**Issue by DMcKinnon-mdsol** [swipely/sumo#12]
Why are the sumo credentials in `~/.sumo_creds`? Isn't the convention to put them in `~/config/sumo_creds.yml`? This is the convention for rails apps, but I think it still flies for non-rails apps.

EDIT: Any chance you could update the gem to look in both locations? I'd like to use this gem, but we don't want to check out credentials into source control, and the tools we use for auto-populating  similar files look in the config directory.

**Comment by nahiluhmot** [comment]
You can set your `ENV['SUMO_CREDENTIAL']` if you don't want to place them into `~/.sumo_creds`.
